spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ewallet_test
    username: postgres
    password: hello123
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false


  flyway:
    out-of-order: true
    baselineOnMigrate: true

